FactoryGirl.define do
  factory :fms_role do
    name "MyString"
    view_employer_profile false
    view_employee_dependent_data false
    view_enrollment_premium_data false
    view_accounts_receivable false
    view_invoices false
    rollback_invoice false
    rebill_invoice false
    view_accounts_payable false
    approve_hr_820 false
    reject_hr_820 false
    regenerate_hr_820 false
    rollback_carrier_820 false
    regenerate_carrier_820 false
    view_memo false
    add_remove_users_and_roles false
    reports false
    enter_employer_notes false
    view_employer_notes "MyString"
    tasks false
    refunds false
    accept_payments false
    allocate_payments false
    monthly_closing false
    yearly_closing false
    view_accounts_payable false
    create_sign_memo false
    save_send_memo false
    record_memo_response false
    reconcile_820 false
    display_invoices_to_pay false
    accept_payment_for_invoices false
    allow_for_onetime_payment false
    allow_for_monthly_recurring_payment false
    transmitted_to_sftp_folder false
    standardized_tbd_file_format false
    provides_payment_amount_emp_gr_invoice_id false
    denotes_payment_data_if_no_match false
    receive_ach_payments false
    send_payment_acknowledgement false
    receive_820_files false
    acknowledge_820_files false
    reconcile_820_and_payments false
    receive_invoice false
    pay_invoice_via_methods false
    receive_print_files_for_invoice false
    print_stuff_mail_invoices false
    support_varying_invoice_freq_emp false
    support_on_demand_print_file_request_for_invoices false
    process_x12_outbound_carrier_820 false
    receive_inbound_carrier_820 ""
    notify_system_of_success_failure_inbound_carrier_response false
    save_copy_of_carrier_repsonse_in_location false
    support_carrier_820_reconciliation_process false
  end
end
